version: 2
updates:
  # Enable version updates for npm (SDK)
  - package-ecosystem: "npm"
    directory: "/sdk"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "Dexploarer"
    assignees:
      - "Dexploarer"
    commit-message:
      prefix: "chore(sdk)"
      include: "scope"

  # Enable version updates for npm (CLI)
  - package-ecosystem: "npm"
    directory: "/cli"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "Dexploarer"
    assignees:
      - "Dexploarer"
    commit-message:
      prefix: "chore(cli)"
      include: "scope"

  # Enable version updates for npm (root)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "Dexploarer"
    assignees:
      - "Dexploarer"
    commit-message:
      prefix: "chore(root)"
      include: "scope"

  # Enable version updates for Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "Dexploarer"
    assignees:
      - "Dexploarer"
    commit-message:
      prefix: "chore(rust)"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "Dexploarer"
    assignees:
      - "Dexploarer"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"