[toolchain]
# Using npm as the package manager (required by Anchor framework - bun not supported)
package_manager = "npm"

[features]
# Enable resolution of Anchor feature flags
resolution = true
# Skip linting during build (set to false for production)
skip-lint = false

# Program configurations for different clusters
[programs.localnet]
pod_com = "HEpGLgYsE1kP8aoYKyLFc3JVVrofS7T4zEA6fWBJsZps"

[programs.devnet]
pod_com = "HEpGLgYsE1kP8aoYKyLFc3JVVrofS7T4zEA6fWBJsZps"

# Registry configuration for Anchor programs
[registry]
url = "https://api.apr.dev"

# Provider configuration
[provider]
# Default cluster to use (devnet, testnet, mainnet-beta, or localnet)
cluster = "devnet"
# Path to the wallet to use for deployment
wallet = "~/.config/solana/id.json"

# Test script configuration
[scripts]
test = "bun test"

# Solana configuration
[solana]
# Enable the new BPF loader (required for Agave)
enable_bpf_loader = true
# Enable the new BPF program deployment
enable_deploy = true
