name: 'Setup Solana Environment'
description: 'Installs Solana, Anchor, and Rust dependencies.'
inputs:
  anchor-version:
    description: 'Version of Anchor CLI to install'
    required: false
    default: '0.31.1'
runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config build-essential libudev-dev

    - name: Install Anchor Version Manager (avm)
      shell: bash
      run: cargo install --git https://github.com/coral-xyz/anchor avm --locked --force

    - name: Install and use specific Anchor version
      shell: bash
      run: |
        avm install ${{ inputs.anchor-version }}
        avm use ${{ inputs.anchor-version }}

    - name: Verify installations
      shell: bash
      run: |
        echo "Solana version: $(solana --version)"
        echo "Anchor version: $(anchor --version)"
        echo "Rust version: $(rustc --version)"
