name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  security-events: write

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18, 20]
        os: [ubuntu-latest, windows-latest, macos-latest]
        solana-version: ['1.16.27', '1.17.0']
        include:
          - os: ubuntu-latest
            node-version: 18
            solana-version: '1.16.27'
            coverage: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Setup Solana
        uses: ./.github/actions/setup-solana
        with:
          solana-version: ${{ matrix.solana-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          npm run lint
          cargo fmt --check
          cargo clippy -- -D warnings

      - name: Build
        run: |
          npm run build:all
          cargo build --release

      - name: Test
        run: |
          npm test
          cargo test

      - name: Test with coverage (Ubuntu only)
        if: matrix.coverage
        run: npm run test:coverage

      - name: Security audit
        run: |
          npm audit --audit-level moderate
          cargo audit

      - name: Upload coverage
        if: matrix.coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info