name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  RUST_BACKTRACE: 1

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Solana
        uses: ./actions/setup-solana
        with:
          solana-version: '1.17.0'

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: bun install

      - name: Install workspace dependencies
        run: |
          cd sdk && bun install
          cd ../cli && bun install

      - name: Lint TypeScript/JavaScript
        run: bun run lint

      - name: Format check Rust
        run: cargo fmt --check
        working-directory: programs/pod-com

      - name: Lint Rust
        run: cargo clippy --all-targets --all-features -- -D warnings
        working-directory: programs/pod-com

      - name: Build all projects
        run: bun run build:all

      - name: Run tests
        run: bun test

      - name: Test Rust
        run: cargo test
        working-directory: programs/pod-com