name: CI
on: [push, pull_request]

jobs:
  lint:
    name: "🎨 Lint & Format"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install JS Dependencies
        run: bun install --frozen-lockfile

      - name: Lint TypeScript & Prettier
        run: bun run lint:all

      - name: Lint Rust
        run: |
          cd programs/pod-com
          cargo fmt -- --check
          cargo clippy -- -D warnings

  build:
    name: "🏗️ Build All"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libudev-dev

      - name: Install Anchor CLI via avm
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          avm install 0.31.1
          avm use 0.31.1

      - name: Install JS Dependencies
        run: bun install --frozen-lockfile

      - name: Build Solana Program
        run: anchor build

      - name: Build SDK
        run: cd sdk && bun run build

      - name: Build CLI
        run: cd cli && bun run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            target/deploy/
            target/idl/
            sdk/dist/
            cli/dist/

  test:
    name: "🧪 Test Suite"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libudev-dev netcat-openbsd

      - name: Install Anchor CLI via avm
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          avm install 0.31.1
          avm use 0.31.1

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Install JS Dependencies
        run: bun install --frozen-lockfile

      - name: Setup Solana keypair
        run: |
          mkdir -p ~/.config/solana
          solana-keygen new --no-bip39-passphrase -o ~/.config/solana/id.json
          solana config set --url localhost

      - name: Start and Wait for Solana Test Validator
        run: |
          solana-test-validator --reset >/dev/null 2>&1 &
          echo "Waiting for validator to be ready..."
          for i in {1..30}; do
            if nc -z localhost 8899; then
              echo "✅ Validator is ready on port 8899"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "❌ Validator did not start within 30 seconds"
              exit 1
            fi
            echo "⏳ Attempt $i/30: Validator not ready yet, waiting..."
            sleep 1
          done

      - name: Run Anchor Tests
        run: anchor test --skip-build

      - name: Run SDK & CLI Tests
        run: bun run test

      - name: Stop Solana test validator
        run: pkill -f solana-test-validator || true