name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust
      run: |
        if ! command -v rustup &>/dev/null; then
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused \
               --location --silent --show-error --fail https://sh.rustup.rs \
               | sh -s -- --default-toolchain none -y || exit 1
        fi

    - name: Install Solana CLI tools
      run: |
        curl -sSf https://release.solana.com/stable/install | bash
        export PATH="$PATH:/home/runner/.local/share/solana/install/active_release/bin"

    - name: Install Anchor CLI
      run: npm install -g @coral-xyz/anchor-cli@0.31.1

    - name: Run Tests
      run: cargo test

    - name: Cleanup
      run: |
        rm -rf /home/runner/work/_temp
        unset CARGO_HOME
