name: Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          cd sdk && npm ci --legacy-peer-deps

      - name: Build documentation
        run: |
          npm run docs || echo "No docs script found, will use README and docs folder"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare documentation files
        run: |
          mkdir -p _site
          if [ -d "docs" ]; then
            cp -r docs/* _site/
          fi
          if [ -f "README.md" ]; then
            cp README.md _site/index.md
          fi
          echo "Documentation prepared for deployment"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
