name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'docs/**'
      - 'README.md'
      - 'sdk/src/**'
      - 'cli/src/**'
      - 'src/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          cd sdk && npm ci --legacy-peer-deps
          cd ../cli && npm ci --legacy-peer-deps

      - name: Generate TypeScript API docs
        run: |
          npm run docs || echo "No root docs script found"
          cd sdk && (npm run docs || echo "No SDK docs script found")
          cd ../cli && (npm run docs || echo "No CLI docs script found")

      - name: Generate Rust docs
        run: cargo doc --no-deps --document-private-items

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4

      - name: Build documentation site
        run: |
          mkdir -p docs-site
          cp -r docs/* docs-site/ 2>/dev/null || true
          cp -r sdk/docs/* docs-site/sdk/ 2>/dev/null || true
          cp -r cli/docs/* docs-site/cli/ 2>/dev/null || true
          cp -r target/doc/* docs-site/rust/ 2>/dev/null || true

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs-site

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
