# NodeJS with Grunt - DISABLED as this project doesn't use Grunt
name: NodeJS with Grunt (DISABLED)

on:
  # Disabled - uncomment if you add Grunt to this project
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:  # Only allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        echo "This workflow is disabled - project doesn't use Grunt"
        echo "If you want to enable this, uncomment the trigger events and update the build commands"
