name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Solana
        uses: ./actions/setup-solana
        with:
          solana-version: stable

      - name: Install Dependencies
        run: bun install

      - name: Build
        run: bun run build:all

      - name: Run Tests
        run: bun test

      - name: Configure npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          
      - name: Publish SDK
        working-directory: sdk
        run: bun run publish --no-git-checks

      - name: Publish CLI
        working-directory: cli
        run: bun run publish --no-git-checks

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
