name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install stable toolchain and required target for cross-compilation
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Add aarch64-apple-darwin target
        run: rustup target add aarch64-apple-darwin

      # (Optional) Install additional toolchains/targets if needed
      # - name: Add other targets
      #   run: rustup target add <other-target>

      - name: Build (default target)
        run: cargo build --verbose

      # If you need to build for the specific target:
      # - name: Build for aarch64-apple-darwin
      #   run: cargo build --target aarch64-apple-darwin --verbose

      - name: Run tests
        run: cargo test --verbose
