name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Linux x86_64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use-cross: false
          - name: Linux aarch64  
            runner: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            use-cross: true
          - name: macOS x86_64
            runner: macos-latest
            target: x86_64-apple-darwin
            use-cross: false
          - name: macOS aarch64
            runner: macos-latest
            target: aarch64-apple-darwin
            use-cross: false
          - name: Windows x86_64
            runner: windows-latest
            target: x86_64-pc-windows-msvc
            use-cross: false

    runs-on: ${{ matrix.runner }}
    name: Build for ${{ matrix.name }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install LLD linker (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y lld
        
    - name: Install cross
      if: matrix.use-cross
      uses: taiki-e/install-action@v2
      with:
        tool: cross
        
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ matrix.runner }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build with cargo
      if: ${{ !matrix.use-cross }}
      run: cargo build --verbose --target ${{ matrix.target }}
      
    - name: Set linker environment for x86_64
      if: matrix.use-cross && matrix.target == 'x86_64-unknown-linux-gnu'
      run: echo "RUSTFLAGS=-C linker=x86_64-linux-gnu-gcc" >> $GITHUB_ENV
      
    - name: Set linker environment for aarch64  
      if: matrix.use-cross && matrix.target == 'aarch64-unknown-linux-gnu'
      run: echo "RUSTFLAGS=-C linker=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        
    - name: Build with cross
      if: matrix.use-cross
      run: cross build --verbose --target ${{ matrix.target }}
      
    - name: Run tests
      if: ${{ !matrix.use-cross }}
      run: cargo test --verbose --target ${{ matrix.target }}
