name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue is stale because it has been open 30 days with no activity. 
            
            If this issue is still relevant, please add a comment to keep it open. 
            Otherwise, it will be automatically closed in 7 days.
          stale-pr-message: |
            This PR is stale because it has been open 30 days with no activity.
            
            If this PR is still relevant, please add a comment to keep it open.
            Otherwise, it will be automatically closed in 7 days.
          close-issue-message: |
            This issue was closed because it has been stalled for 7 days with no activity.
            
            If you believe this issue should remain open, please reopen it with additional context.
          close-pr-message: |
            This PR was closed because it has been stalled for 7 days with no activity.
            
            If you believe this PR should remain open, please reopen it with additional context.
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'pinned,security,enhancement'
          exempt-pr-labels: 'pinned,security'